<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_id' => 'SUP-0001',
                'company_name' => 'Meghna Group of Industries (Fresh & Teer)',
                'contact_person' => 'Md. Faruq Ahmed',
                'phone' => '+8801819000001',
                'email' => 'distribution@meghnagroup.com',
                'address' => 'Fresh Villa, House 15, Road 34, Gulshan-1, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 12500.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0002',
                'company_name' => 'Pran-RFL Consumer Goods & Beverage',
                'contact_person' => 'Tanvir Hasan',
                'phone' => '+8801819000002',
                'email' => 'sales@pranfoods.net',
                'address' => 'PRAN-RFL Center, 105 Middle Badda, Dhaka-1212',
                'opening_balance' => 0.00,
                'current_payable_balance' => 8400.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0003',
                'company_name' => 'Unilever Bangladesh Ltd',
                'contact_person' => 'Shahriar Rahman',
                'phone' => '+8801819000003',
                'email' => 'fmcg.supply@unilever.com',
                'address' => 'ZN Tower, Plot 2, Road 8, Gulshan-1, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 18600.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0004',
                'company_name' => 'Square Food & Beverage Ltd',
                'contact_person' => 'Khandaker Rafiqul Islam',
                'phone' => '+8801819000004',
                'email' => 'orders@squarefood.com',
                'address' => 'Square Centre, 48 Mohakhali C/A, Dhaka-1212',
                'opening_balance' => 0.00,
                'current_payable_balance' => 14200.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0005',
                'company_name' => 'Nestle Bangladesh Plc',
                'contact_person' => 'Nusrat Jahan',
                'phone' => '+8801819000005',
                'email' => 'supplychain@bd.nestle.com',
                'address' => 'Shanta Western Tower, Level 4, Bir Uttam Mir Shawkat Sarak, Tejgaon, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 21500.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0006',
                'company_name' => 'Aarong Dairy & BRAC Enterprises',
                'contact_person' => 'Mustafizur Rahman',
                'phone' => '+8801819000006',
                'email' => 'aarong.dairy@brac.net',
                'address' => 'Aarong Centre, 346 Tejgaon I/A, Dhaka-1208',
                'opening_balance' => 0.00,
                'current_payable_balance' => 9750.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0007',
                'company_name' => 'City Group of Industries',
                'contact_person' => 'Kamal Hossain',
                'phone' => '+8801819000007',
                'email' => 'sales@citygroup.com.bd',
                'address' => 'City House, Plot 83, Road 11, Block D, Banani, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 16300.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0008',
                'company_name' => 'Akij Food & Beverage Ltd',
                'contact_person' => 'Mahbub Alam',
                'phone' => '+8801819000008',
                'email' => 'afbl.orders@akij.net',
                'address' => 'Akij House, 198 Bir Uttam Mir Shawkat Sarak, Tejgaon, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 11200.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0009',
                'company_name' => 'ACI Consumer Brands & Logistics',
                'contact_person' => 'Syed Monirul Islam',
                'phone' => '+8801819000009',
                'email' => 'consumer.logistics@aci-bd.com',
                'address' => 'ACI Centre, 245 Tejgaon Industrial Area, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 15400.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0010',
                'company_name' => 'Bashundhara Food & Beverage Industries',
                'contact_person' => 'Imtiaz Ahmed',
                'phone' => '+8801819000010',
                'email' => 'bfbil.distribution@bgd-world.com',
                'address' => 'Bashundhara Industrial Complex, Baridhara, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 13800.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0011',
                'company_name' => 'Olympic Industries Ltd',
                'contact_person' => 'Zubair Hossain',
                'phone' => '+8801819000011',
                'email' => 'sales@olympicbd.com',
                'address' => 'Amin Court, 6th Floor, 62-63 Motijheel C/A, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 7600.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0012',
                'company_name' => 'Marico Bangladesh Ltd',
                'contact_person' => 'Sabbir Ahmed',
                'phone' => '+8801819000012',
                'email' => 'commercial@maricobd.com',
                'address' => 'The Glass House, Level 6, Plot 2, Block SE(B), Gulshan-1, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 9200.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0013',
                'company_name' => 'Reckitt Benckiser Bangladesh Plc',
                'contact_person' => 'Farhana Sultana',
                'phone' => '+8801819000013',
                'email' => 'orders.bd@reckitt.com',
                'address' => 'The Pearl Trade Center, Level 10, Cha-90/3 Pragati Sarani, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 11900.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0014',
                'company_name' => 'Kazi Farms Group (Poultry & Frozen)',
                'contact_person' => 'Kazi Enamul Haque',
                'phone' => '+8801819000014',
                'email' => 'supply@kazifarms.com',
                'address' => 'House 35, Road 71, Gulshan-2, Dhaka-1212',
                'opening_balance' => 0.00,
                'current_payable_balance' => 17400.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0015',
                'company_name' => 'CP Bangladesh Co. Ltd (Fresh & Processed Meat)',
                'contact_person' => 'Arunav Dey',
                'phone' => '+8801819000015',
                'email' => 'sales@cpbangladesh.com',
                'address' => 'Plot 6, Block C, Sector 1, Uttara, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 13100.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0016',
                'company_name' => 'Bengal Meat Processing Industries Ltd',
                'contact_person' => 'A. F. M. Asaduzzaman',
                'phone' => '+8801819000016',
                'email' => 'corporate.sales@bengalmeat.com',
                'address' => 'House 14, Road 113/A, Gulshan-2, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 22800.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0017',
                'company_name' => 'Abul Khair Consumer Products (Marks & Ceylon)',
                'contact_person' => 'Jahangir Kabir',
                'phone' => '+8801819000017',
                'email' => 'consumer.supply@abulkhairgroup.com',
                'address' => 'Navana Tower, 45 Gulshan Avenue, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 14500.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0018',
                'company_name' => 'Transcom Beverages Ltd (PepsiCo Partner)',
                'contact_person' => 'Rizwanur Rahman',
                'phone' => '+8801819000018',
                'email' => 'tbl.orders@transcombd.com',
                'address' => 'Transcom House, 52 Motijheel C/A, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 19300.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0019',
                'company_name' => 'Coca-Cola Bangladesh Beverages Ltd',
                'contact_person' => 'Shamim Reza',
                'phone' => '+8801819000019',
                'email' => 'distribution@coca-cola.com.bd',
                'address' => 'Abdul Monem Financial District, 111 Bir Uttam C.R. Dutta Road, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 18900.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0020',
                'company_name' => 'Bombay Sweets & Co. Ltd',
                'contact_person' => 'Tariqul Islam',
                'phone' => '+8801819000020',
                'email' => 'sales@bombaysweetsbd.com',
                'address' => 'Baitul View Tower, 56/1 Purana Paltan, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 6400.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0021',
                'company_name' => 'Ispahani Tea & Agro Ltd',
                'contact_person' => 'Mirza Salman',
                'phone' => '+8801819000021',
                'email' => 'tea.orders@ispahanibd.com',
                'address' => 'Ispahani Building, 14/15 Motijheel C/A, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 8800.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0022',
                'company_name' => 'Danish Foods Ltd & Partex Star',
                'contact_person' => 'Monjur Elahi',
                'phone' => '+8801819000022',
                'email' => 'danish@partexstar.com',
                'address' => 'Shanta Western Tower, Level 10, Tejgaon, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 7900.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0023',
                'company_name' => 'Haque Food Industries Ltd',
                'contact_person' => 'Anisul Haque',
                'phone' => '+8801819000023',
                'email' => 'marketing@haquegroup.com',
                'address' => 'Haque Chamber, 89/2 West Panthapath, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 5200.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0024',
                'company_name' => 'Kohinoor Chemical Co. (BD) Ltd (Tibet & Sandalina)',
                'contact_person' => 'Zahirul Islam',
                'phone' => '+8801819000024',
                'email' => 'sales@kohinoor-bd.com',
                'address' => 'Kohinoor Bhaban, 36 Shahid Tajuddin Ahmed Sarani, Tejgaon, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 8600.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0025',
                'company_name' => 'Sajeeb Group & Shezan Foods',
                'contact_person' => 'Hashem Ali',
                'phone' => '+8801819000025',
                'email' => 'orders@sajeebgroup.com.bd',
                'address' => 'Shezan Point, 2 Indira Road, Farmgate, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 9100.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0026',
                'company_name' => 'Golden Harvest Agro Industries Ltd',
                'contact_person' => 'Samir Das',
                'phone' => '+8801819000026',
                'email' => 'frozenfoods@goldenharvestbd.com',
                'address' => 'Shanta Western Tower, Level 5, Tejgaon I/A, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 10500.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0027',
                'company_name' => 'Dhaka Fresh Produce & Organic Farm Network',
                'contact_person' => 'Abdur Rahim Matubbar',
                'phone' => '+8801819000027',
                'email' => 'freshproduce@dhakafarms.com',
                'address' => 'Karwan Bazar Wholesale Vegetable Hub, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 14800.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0028',
                'company_name' => 'Coastal Fisheries & Riverine Seafood Supply',
                'contact_person' => 'Golam Mostafa',
                'phone' => '+8801819000028',
                'email' => 'seafood.supply@coastalfish.com.bd',
                'address' => 'Jatrabari Wholesale Fish Terminal, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 24500.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0029',
                'company_name' => 'Apex Paper, Labels & POS Thermal Supplies',
                'contact_person' => 'Nasir Uddin',
                'phone' => '+8801819000029',
                'email' => 'pos.supplies@apexpackaging.com',
                'address' => 'Arambagh Printing Hub, Motijheel, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 4200.00,
                'status' => 'active',
            ],
            [
                'supplier_id' => 'SUP-0030',
                'company_name' => 'SuperClean Industrial Chemicals & Hygiene Care',
                'contact_person' => 'Engr. Tariq Mahmud',
                'phone' => '+8801819000030',
                'email' => 'clean.hygiene@supercleanbd.com',
                'address' => 'Hazaribagh Industrial Zone, Dhaka',
                'opening_balance' => 0.00,
                'current_payable_balance' => 6100.00,
                'status' => 'active',
            ],
        ];

        foreach ($suppliers as $s) {
            Supplier::query()->updateOrCreate(
                ['supplier_id' => $s['supplier_id']],
                $s
            );
        }
    }
}
